In [1]:
import numpy as np
import pandas as pd

In [12]:
data = {
    'Name' : ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
    'Math' : [85, 90, np.nan, 75, 65, 200, 70],
    'English' : [88, 92, 95, 67, np.nan, 63, 77],
    'Science' : [78, 85, 82, 60, 90, 88, np.nan]
}

In [13]:
df = pd.DataFrame(data)
df

  Name   Math  English  Science
0    A   85.0     88.0     78.0
1    B   90.0     92.0     85.0
2    C    NaN     95.0     82.0
3    D   75.0     67.0     60.0
4    E   65.0      NaN     90.0
5    F  200.0     63.0     88.0
6    G   70.0     77.0      NaN

In [14]:
df.isnull().sum()

Name       0
Math       1
English    1
Science    1
dtype: int64

In [15]:
df['Math'] = df['Math'].fillna(df['Math'].mean())
df

  Name   Math  English  Science
0    A   85.0     88.0     78.0
1    B   90.0     92.0     85.0
2    C   97.5     95.0     82.0
3    D   75.0     67.0     60.0
4    E   65.0      NaN     90.0
5    F  200.0     63.0     88.0
6    G   70.0     77.0      NaN

In [16]:
df['English'].fillna(df['English'].median(), inplace=True)
df

C:\Users\Dilshad Ansari\AppData\Local\Temp\ipykernel_29788\374531831.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['English'].fillna(df['English'].median(), inplace=True)

  Name   Math  English  Science
0    A   85.0     88.0     78.0
1    B   90.0     92.0     85.0
2    C   97.5     95.0     82.0
3    D   75.0     67.0     60.0
4    E   65.0     82.5     90.0
5    F  200.0     63.0     88.0
6    G   70.0     77.0      NaN

In [17]:
df['Science'] = df['Science'].fillna(df['Science'].median())
df

  Name   Math  English  Science
0    A   85.0     88.0     78.0
1    B   90.0     92.0     85.0
2    C   97.5     95.0     82.0
3    D   75.0     67.0     60.0
4    E   65.0     82.5     90.0
5    F  200.0     63.0     88.0
6    G   70.0     77.0     83.5

In [28]:
df['Math'] = df['Math'].apply(lambda x: 100 if x > 100 else x)
df

  Name   Math  English  Science
0    A   85.0     88.0     78.0
1    B   90.0     92.0     85.0
2    C   97.5     95.0     82.0
3    D   75.0     67.0     60.0
4    E   65.0     82.5     90.0
5    F  100.0     63.0     88.0
6    G   70.0     77.0     83.5

In [29]:
Q1 = df['Math'].quantile(0.25)
Q2 = df['Math'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(lower, upper)

40.625 125.625

In [30]:
df['Math'] = np.where(df['Math'] > upper, upper, df['Math'])

In [27]:
df

  Name   Math  English  Science
0    A   85.0     88.0     78.0
1    B   90.0     92.0     85.0
2    C   97.5     95.0     82.0
3    D   75.0     67.0     60.0
4    E   65.0     82.5     90.0
5    F  100.0     63.0     88.0
6    G   70.0     77.0     83.5

In [33]:
df['Math_normalized'] = (df['Math'] - df['Math'].min()) / (df['Math'].max() - df['Math'].min())
df['Math_log'] = np.log(df['Math'])
df

  Name   Math  English  Science  Math_normalized  Math_log
0    A   85.0     88.0     78.0         0.571429  4.442651
1    B   90.0     92.0     85.0         0.714286  4.499810
2    C   97.5     95.0     82.0         0.928571  4.579852
3    D   75.0     67.0     60.0         0.285714  4.317488
4    E   65.0     82.5     90.0         0.000000  4.174387
5    F  100.0     63.0     88.0         1.000000  4.605170
6    G   70.0     77.0     83.5         0.142857  4.248495